version: 0.0
os: windows
files:
  - source: web\web.config
    destination: c:\inetpub\wwwroot\web
  - source: web\config.json
    destination: c:\inetpub\wwwroot\web
  - source: web\bin
    destination: c:\inetpub\wwwroot\web\bin
  - source: web\paket.references
    destination: c:\inetpub\wwwroot\web
  - source: web\Website.csproj
    destination: c:\inetpub\wwwroot\web
  - source: web\Assets\Styles\*.less
    destination: c:\inetpub\wwwroot\web\Assets\Styles
  - source: web\Templates
    destination: c:\inetpub\wwwroot\web\Templates

  - source: .paket\paket.exe
    destination: c:\inetpub\wwwroot\.paket
  - source: paket.lock
    destination: c:\inetpub\wwwroot
  - source: paket.dependencies
    destination: c:\inetpub\wwwroot
  - source: DeployPackages.exe
    destination: c:\inetpub\wwwroot

hooks:
  ApplicationStop:
    - location: scripts/CodeDeploy-stop.cmd
      timeout: 300

  ApplicationStart:
    - location: scripts/CodeDeploy-start.cmd
      timeout: 300
